# Generated by Django 3.1.4 on 2021-01-03 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20210103_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('bottle', 'Butelka'), ('keg', 'Keg')], default='bottle', max_length=7)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('boxquantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_distribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-beer', 'package'),
            },
        ),
    ]
