# Generated by Django 3.1.4 on 2021-01-04 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20210103_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('złożone', 'Złożone'), ('zrealizowane', 'Zrealizowane'), ('anulowane', 'Anulowane')], default='Złożone', max_length=12)),
                ('totalamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdon',),
            },
        ),
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ('beer', 'package')},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='package',
            field=models.CharField(choices=[('butelka', 'Butelka'), ('keg', 'Keg')], default='bottle', max_length=7),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_stock', to='orders.distribution')),
            ],
            options={
                'ordering': ('distribution',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beer_order', to='orders.distribution')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.order')),
            ],
            options={
                'ordering': ('-order', 'distribution'),
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('productiondate', models.DateField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_lot', to='orders.distribution')),
            ],
            options={
                'ordering': ('-productiondate',),
            },
        ),
    ]
