# Generated by Django 3.1.4 on 2021-01-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210104_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
